name: adaptive_dashboard_shell_example
description: Example app for the adaptive_dashboard_shell package.
publish_to: "none"
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_dashboard_shell:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
